L34
Osshrp/qna pull request #11
Opened 2017-06-11 12:02 UTC by Osshrp

2017-06-11 14:06 UTC, vkurennov requested changes
Исправь замечания и в видах тоже нужно проверки сделать при помощи CanCan

2017-06-11 14:06 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    respond_with(@answer.update(answer_params)) if current_user.author_of?(@answer)
Теперь все эти проверки на `author_of?`  нужно заменить на CanCan, в самом Ability этот метод можно использовать, если нужно, но авторизация должна проходить только через CanCan

2017-06-11 14:06 UTC, vkurennov commented on app/controllers/application_controller.rb
> +    redirect_to questions_path, alert: exception.message
Нужно сделать обработчики для всех форматов - html, js, json

2017-06-12 10:50 UTC, vkurennov requested changes

2017-06-12 10:50 UTC, vkurennov commented on app/controllers/comments_controller.rb
> +    authorize! :destroy, @comment
Если вынести загрузку объекта в филтр, то не придется вызывать врунчую `authorize!`, т.к. будет правильно работать `authorize_resource`

2017-06-12 10:50 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +      if can? :vote, @votable
Ну вообще, тут тоже через `authorize!` надо сделать.

2017-06-12 10:50 UTC, vkurennov commented on app/models/ability.rb
> +      attachment.attachable.user_id == user.id
А чего метод `author_of?` не применил?

2017-06-12 11:07 UTC, Osshrp commented on app/controllers/comments_controller.rb
> +    authorize! :destroy, @comment
Точно!  Я забыл, что authorize_resource объекты не загружает)

2017-06-12 12:01 UTC, vkurennov approved these changes

2017-06-12 12:36 UTC, merged