to home
Osshrp/qna pull request #15
Opened 2017-06-21 13:20 UTC by Osshrp

2017-06-25 17:54 UTC, iBublik requested changes

2017-06-25 17:54 UTC, iBublik commented on app/controllers/subscriptions_controller.rb
> +    @subscription = @question.subscriptions.create(user: current_user)
Я бы создавал подписки так - `current_user.subscriptions.new(question: @question)`. Чисто логически подписка скорее принадлежит юзеру, а не вопросу

2017-06-25 17:54 UTC, iBublik commented on app/jobs/answer_notification_job.rb
> +    answer.question.subscriptions.each do |subscription|
Добавь `includes(:user)`, чтоб тут N+1 запросов не было

2017-06-25 17:54 UTC, iBublik commented on app/jobs/daily_digest_job.rb
> +    questions = Question.where('created_at > ?', 1.day.ago)
Это можно в скоуп вынести, чтоб логика выборки в модели лежала

2017-06-25 17:54 UTC, iBublik commented on config/routes.rb
> +    resources :subscriptions, shallow: true, only: [:create, :destroy]
Вообще это можно было организовать как `resource :subscription`. Ведь к 1 вопросу может быть только 1 подписка у текущего пользователя.

2017-06-25 17:54 UTC, iBublik commented on app/controllers/subscriptions_controller.rb
> +    @subscription = @question.subscriptions.create(user: current_user)
Хотя у тебя есть удобные методы в модели, с ними будет лучше. Зря не использовал :)

2017-06-25 17:54 UTC, iBublik commented on app/models/question.rb
> +  def subscribe(user)
Методы удобные, но нигде кроме тестов не используются.

2017-06-25 17:54 UTC, iBublik commented on app/models/question.rb
> +    subscriptions.where(user: user).first.destroy
Можно `find_by` использовать как замену `where(...).first`

2017-06-25 17:54 UTC, iBublik commented on app/models/user.rb
> +    subscriptions.where(question: question, user: self).first.blank?
`subscriptions.where(question: question).exists?` - сделает то же самое без загрузки ассоциации в память. А `user: self` вообще лишнее, у тебя ведь ассоциация `subscriptions` уже делает запрос на подписки текущего пользователя

2017-06-25 17:54 UTC, iBublik commented on app/models/user.rb
> +  def unsubscribed_from?(question)
Я бы сделал метод `subscribed_to?(question)` - как-то логичнее кажется проверять есть ли подписка у пользователя, а не ее отсутствие.

2017-06-25 17:54 UTC, iBublik commented on app/mailers/answer_mailer.rb
> +    @greeting = "Hi"
А есть смысл это в переменную выносить?

2017-06-25 17:54 UTC, iBublik commented on Gemfile
> +gem 'sidetiq'
Sidetiq уже не поддерживается, я бы не стал его в проект добавлять

2017-06-25 17:54 UTC, iBublik commented on app/views/answer_mailer/notify.html.slim
> +p = @greeting + ", the question #{@answer.question.title} has new answer"
Вот `@answer.question.title` как раз можно в переменную вынести, раз 2 раза используется

2017-06-25 17:54 UTC, iBublik commented on bin/delayed_job
> +#!/usr/bin/env ruby
Убери, раз используешь sidekiq. И вьюхи для подписок тоже убери, они не используются

2017-06-25 17:54 UTC, iBublik commented on config/schedule.rb
> +every 1.days do
`every :day`

2017-06-25 17:54 UTC, iBublik commented on db/migrate/20170621060243_create_delayed_jobs.rb
> +class CreateDelayedJobs < ActiveRecord::Migration[5.0]
Зачем нам мертвая таблица в БД?

2017-06-25 17:54 UTC, iBublik commented on db/migrate/20170622111024_add_user_id_to_subscriptions.rb
> +    add_belongs_to :subscriptions, :user
Схлопни в одну миграцию с созданием подписок и добавь вешние ключи. Так же стоит уникальный индекс навесить на связку `user_id, question_id` - только так обеспечивается реальная уникальность записей. Рельсовая валидация уникальности может не успеть отработать, если две одинаковые записи будут добавляться одновременно. В случае с подписками такое вряд ли возможно, но это просто хорошая практика.

2017-06-25 17:54 UTC, iBublik commented on dump.rdb
> +REDIS0006�ܳC�Z��V
Это в .gitignore

2017-06-25 17:54 UTC, iBublik commented on spec/api/v1/answers_spec.rb
> +            to be_json_eql(answers.first.send(attr.to_sym).to_json).at_path("answers/0/#{attr}")
Тут наверно плавающая ошибка наблюдается. Можешь добавить сортировку по дате создания и в спеках создать ответы с разной датой, тогда они всегда будут проходить

2017-06-25 17:54 UTC, iBublik commented on spec/models/user_spec.rb
> +    it 'should return false if user is subscribed to question' do
Нужно добавить позитивный сценарий

2017-06-25 17:54 UTC, iBublik commented on spec/controllers/subscriptions_controller_spec.rb
> +            .to change(question.subscriptions, :count).by(-1)
При удалении лучше проверять изменение общего числа вопросов. Так мы гарантируем, что мы не просто изменили ассоциацию, а именно удалили объект с концами.

2017-06-27 16:32 UTC, Osshrp commented on db/migrate/20170622111024_add_user_id_to_subscriptions.rb
> +    add_belongs_to :subscriptions, :user
При наличии внешних ключей не проходит тест на валидацию уникальности
```
Failure/Error: it { should validate_uniqueness_of(:question_id).scoped_to(:user_id) }
     
     ActiveRecord::InvalidForeignKey:
       PG::ForeignKeyViolation: ERROR:  insert or update on table "subscriptions" violates foreign key constraint "fk_rails_3f3e620f91"
       DETAIL:  Key (question_id)=(0) is not present in table "questions".
       : UPDATE "subscriptions" SET "question_id" = $1, "updated_at" = $2 WHERE "subscriptions"."id" = $3
```

2017-06-27 16:37 UTC, Osshrp commented on spec/controllers/subscriptions_controller_spec.rb
> +            .to change(question.subscriptions, :count).by(-1)
Вот тут не понял.
я же удаляю подписку, причем здесь общее число вопросов? Или это опечатка.
Наверное число подписок.

2017-06-27 16:55 UTC, Osshrp commented on spec/api/v1/answers_spec.rb
> +            to be_json_eql(answers.first.send(attr.to_sym).to_json).at_path("answers/0/#{attr}")
Добавил сортировку и тут такое началось….
Упали все тесты, где сортировка влияла. Замучился разбираться.
Вернул все обратно

2017-06-27 18:42 UTC, iBublik commented on app/mailers/daily_mailer.rb
> +    @greeting = "Hi"
И все же зачем это в инстанс переменную выносить? :)

2017-06-27 18:42 UTC, iBublik commented on app/models/daily_digest_worker.rb
> +class DailyDigestWorker
Что это за класс вообще? Нигде не используется, содержит нерабочий код

2017-06-27 18:42 UTC, iBublik commented on app/controllers/subscriptions_controller.rb
> +    respond_with(@subscription.question.unsubscribe(current_user)) do |format|
Грузим подписку, потом вопрос к которому она прикреплена, потом вызываем метод, в котором грузится подписка переданного юзера... Как-то сложно слишком. Если уж передаешь id в роутах, то просто грохни подписку с указанным id

2017-06-27 18:42 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    @subscription = @question.subscriptions.where(user: current_user).first
`find_by(user: current_user)`

2017-06-27 18:42 UTC, iBublik commented on app/models/user.rb
> +    subscriptions.find_by(question: question).present?
`subscriptions.where(question: question).exists?` - нам не надо грузить ассоциацию, достаточно запрос на наличие в базу отправить

2017-06-27 18:42 UTC, iBublik commented on dump.rdb
> +REDIS0006�ܳC�Z��V
Дамп по-прежнему в репозитории. `git rm dump.rdb --cached` уберет файл из индекса, но не с диска

2017-06-27 19:28 UTC, vkurennov approved these changes

2017-06-28 14:52 UTC, merged