L39
Osshrp/qna pull request #16
Opened 2017-07-02 14:25 UTC by Osshrp

2017-07-02 18:48 UTC, iBublik requested changes

2017-07-02 18:48 UTC, iBublik commented on app/controllers/searches_controller.rb
> +    @region = params[:scope]
Не очень нравится нейминг, может лучше использовать `resource`?

2017-07-02 18:48 UTC, iBublik commented on app/services/search.rb
> +      attr = %w(all questions answers comments users)
Это можно вынести в константу и дать более понятный нейминг, а то `attr` вообще что-то абстрактное :)

2017-07-02 18:48 UTC, iBublik commented on app/services/search.rb
> +      string.sub(/\S/, &:upcase)
Я не смог понять в чем суть этого метода :) Чем обычный `capitalize` не подошел?

2017-07-02 18:48 UTC, iBublik commented on app/services/search.rb
> +    def klass(string)
У рельсы есть метод `classify` для строки - приводит ее в принятый формат именования классов.
А вообще у `ThinkingSphinx` есть параметр `classes:`, можно так писать: `ThinkingSphinx.search escaped_query, classes: ...`

2017-07-02 18:48 UTC, iBublik commented on spec/acceptance/search_spec.rb
> +  # given!(:comment) { create(:comment, commentable: answer,
Зачем этот комментарий?

2017-07-02 18:48 UTC, iBublik commented on spec/acceptance/search_spec.rb
> +feature 'Search', %q{
В это спеке лучше сделать так:
1. Задать всем сущностям общую часть в заголовках/телах
2. В тестет на общий поиск искать эту общую часть и проверить, что вывелись все типы сущностей
3. В остальных тестах проверить, что вывелся _только выбранный_ тип сущности

2017-07-03 06:26 UTC, Osshrp commented on app/services/search.rb
> +    def klass(string)
Забыл про classify, причем раньше его применял, а теперь вылетело из головы :)

2017-07-03 06:27 UTC, Osshrp commented on app/services/search.rb
> +      string.sub(/\S/, &:upcase)
Опять забыл. Забыл, что есть capitalize и стал изобретать велосипед :)

2017-07-03 09:00 UTC, vkurennov approved these changes

2017-07-03 11:26 UTC, merged