L26 acceptance tests
Osshrp/qna pull request #3
Opened 2017-04-25 11:54 UTC by Osshrp

2017-04-26 04:15 UTC, webmstk commented on spec/support/acceptance_helper.rb
> +  end
Эти методы специфичны для конкретных тестов, не надо выносить их в хелпер. Лучше определи их в тестах, где они используются.

2017-04-26 06:57 UTC, iBublik requested changes

2017-04-26 06:57 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    @answer.destroy
Нужна проверка, что пользователь явялется автором ответа.

2017-04-26 06:57 UTC, iBublik commented on app/controllers/questions_controller.rb
>      if @question.update(question_params)
Логично было бы позволять редактировать вопрос только тому, кто его создал

2017-04-26 06:57 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    flash[:alert] = @question.errors.full_messages
Это сообщение будет выведено только после редиректа, а ты используешь его при рендере. Почитай про флеши [тут](http://guides.rubyonrails.org/action_controller_overview.html#the-flash)

2017-04-26 06:57 UTC, iBublik commented on app/views/answers/show.html.slim
> +- if current_user == @answer.user
Эту проверку надо и в контроллере сделать. И будет удобнее вынести в метод, чтоб не дублировать код

2017-04-26 06:57 UTC, iBublik commented on app/views/questions/show.html.slim
> +    - @question.answers.each do |answer|
В `show` ты билдишь новый ответ, он тоже попадет в этот список. Нужно выводить только сохраненные ответы

2017-04-26 06:57 UTC, iBublik commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to have_content 'Answer text'
Добавь еще проверку на наличие сообщения об успехе. Иначе возможна ситуация - ты добавил новую валидацию в модель ответа, она не прошла, отрендерилась эта же строничка с ошибками и текстом `Answer text` в инпуте. В этом случае этот тест все равно пройдет

2017-04-26 06:57 UTC, iBublik commented on spec/acceptance/create_question_spec.rb
> +  def ask_question_link
Назоваи `click_ask_question_link`, а то непонятно что этот метод делает - создается впечатление, что просто ссылку возвращает

2017-04-26 06:57 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
Нужна проверка, что пользователь может удалить только свой ответ

2017-04-26 06:57 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
>    describe 'POST #create' do
Еще нужно проверить, что ответ привязался к пользователю

2017-04-26 06:57 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
>    describe 'POST #create' do
Здесь тоже надо проверить, что ответ привязался к пользователю

2017-04-26 06:57 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +    before do
Не нужно дублировать код хелпера. Либо сделай, чтоб хелпер мог принимать юзера, которого логинит, либо просто создай вопросы для залогиненного юзера

2017-04-26 06:57 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
Нужно проверить, что только автор может удалять вопрос

2017-04-26 08:02 UTC, Osshrp commented on app/controllers/questions_controller.rb
> +    flash[:alert] = @question.errors.full_messages
Почитал, но почемуто сообщение выводится и в такой реализации, странно.

2017-04-26 11:21 UTC, Osshrp commented on app/controllers/questions_controller.rb
>      if @question.update(question_params)
Это код из скрикаста.
В задании истории про редактирование нет, поэтому я оставил как есть

2017-04-26 18:50 UTC, iBublik commented on app/views/answers/show.html.slim
> +- if current_user == @answer.user
С методом все-таки было бы лучше :) Что-то типа в модели User
```ruby
def author_of?(entity)
  entity.user_id == id
end
```
Ну и использовать это везде для проверок (и для вопросов, и для ответов) - во вьюхах и контроллерах

2017-04-26 18:50 UTC, iBublik commented on app/views/questions/show.html.slim
> +      - unless answer.new_record?
Можно было сделать `@question.answers.reject(&:new_record?).each ...`

2017-04-26 18:50 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer).user).to eq @user
Можно было просто модифицировать тест выше - `expect { ... }.to change(@user.answers, :count).by(1)`

2017-04-26 18:50 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +    it 'deletes answer by another user' do
В описании теста должно отражаться ожидаемое поведение - т.е., что юзер не может удалить ответ другого юзера. И вообще лучше разнести на 2 контекста, как мы делали с валидными/невалидными ответами - один для удаления своих ответов, другой для удаления чужих ответов

2017-04-26 18:50 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +        expect(assigns(:question).user).to eq @user
Тут рекомендация аналогична тестам ответов

2017-04-26 18:50 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +        .to change(Answer, :count).by(0)
`to_not change(Answer, :count)`

2017-04-26 18:50 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +      @user.questions.create(attributes_for(:question, user: @user))
`create :question, user: @user`

2017-04-26 19:09 UTC, vkurennov requested changes

2017-04-26 19:09 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def show
У ответа нет show, они же все выводятся на странице вопроса

2017-04-26 19:09 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question
Если делать редирект, то потеряется вся информация об ошибках валидации, поэтому нужен рендер той страницы, где форма

2017-04-26 19:09 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user == @answer.user
1. Вынеси в метод, как советовал @iBublik 
2. Лучше сравнивать по id, чтобы не тянуть из базы не нужную ассоциацию у ответа

2017-04-26 19:09 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    current_user == @question.user ? true : false
1. Используй метод для сравнения, т.к. проверка уже не первый раз повторяется
2. Не надо использовать тренарный оператор, операция сравнения и так вернет true или false, надо просто сравнить и все, больше ничего делать не нужно.
3. вот такие имена методов практически напрямую указывают, что метод не в том месте. Ведь логичнее тогда и вызывать у user'а подобный метод. Ну точнее, у current_user, например, `current_user.has_rights?`. Но лучше сделать метод `author_of?`, он лучше отражает суть

2017-04-26 19:09 UTC, vkurennov commented on app/views/answers/show.html.slim
> +- if current_user == @answer.user
Да-да, метод нужен

2017-04-26 19:09 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    - if current_user == @question.user
Замени на метод

2017-04-26 19:09 UTC, vkurennov commented on app/views/questions/show.html.slim
> +      - unless answer.new_record?
Ну это дело вкуса, но я бы тут зменил проверку на `if answer.persisted?`

2017-04-26 19:09 UTC, vkurennov commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to have_content "Body can't be blank"
А этот тест проходит? Ведь у тебя в случае невалидного ответа просто просиходит редирект

2017-04-26 19:09 UTC, vkurennov commented on spec/acceptance/delete_spec.rb
> +  scenario 'Author tries to delete his question' do
Это две разные фичи - удаление вопросов и удаление ответов, надо разнести по разным спекам

2017-04-26 19:09 UTC, vkurennov commented on spec/acceptance/view_question_spec.rb
> +    expect(page).to have_content 'AnswerText'
Тут надо список ответов проверить, создай несколько, причем разных и проверь, что все есть на станице. Тут подойдет sequence в фабриках, чтобы создавать уникальные ответы

2017-04-26 19:09 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>            .to change(Answer, :count).by(1)
Надо проверить, что овтет связывается с вопросом

2017-04-26 19:09 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    it 'deletes answer by another user' do
Поддерживаю

2017-04-26 19:09 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
И также сделать 2 контекста: для автора и для не автора

2017-04-27 06:28 UTC, Osshrp commented on spec/controllers/questions_controller_spec.rb
> +      @user.questions.create(attributes_for(:question, user: @user))
Так не выходит:
`Failure/Error: @user.questions.create(:question, user: @user)
     
     ArgumentError:
       wrong number of arguments (given 2, expected 0..1)
`

2017-04-27 06:29 UTC, Osshrp commented on app/views/answers/show.html.slim
> +- if current_user == @answer.user
Создал метод

2017-04-27 06:29 UTC, Osshrp commented on app/views/questions/show.html.slim
> +    - @question.answers.each do |answer|
исправил

2017-04-27 06:29 UTC, Osshrp commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to have_content 'Answer text'
done

2017-04-27 06:30 UTC, Osshrp commented on spec/controllers/answers_controller_spec.rb
>    describe 'POST #create' do
Сделал

2017-04-27 06:30 UTC, Osshrp commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
Done

2017-04-27 06:30 UTC, Osshrp commented on spec/controllers/questions_controller_spec.rb
>    describe 'POST #create' do
Done

2017-04-27 06:30 UTC, Osshrp commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
Сделал

2017-04-27 06:30 UTC, Osshrp commented on app/views/questions/show.html.slim
> +      - unless answer.new_record?
Ок, изменил

2017-04-27 06:31 UTC, Osshrp commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer).user).to eq @user
Done

2017-04-27 06:31 UTC, Osshrp commented on spec/controllers/answers_controller_spec.rb
> +    it 'deletes answer by another user' do
Сделал

2017-04-27 06:31 UTC, Osshrp commented on spec/controllers/answers_controller_spec.rb
> +        .to change(Answer, :count).by(0)
Сделал

2017-04-27 06:31 UTC, Osshrp commented on spec/controllers/questions_controller_spec.rb
> +        expect(assigns(:question).user).to eq @user
Исправил

2017-04-27 06:32 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +    if current_user == @answer.user
Сделал

2017-04-27 06:33 UTC, Osshrp commented on app/views/questions/show.html.slim
> +    - if current_user == @question.user
Сделал

2017-04-27 06:35 UTC, Osshrp commented on app/controllers/questions_controller.rb
> +    current_user == @question.user ? true : false
Сделал

2017-04-27 06:47 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +  def show
Ну, почему же, есть show. Можно зайти в ответ и удалить его отуда
И на это тесты написаны

2017-04-27 06:52 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +      redirect_to @question
Странно, сообщение об ошибке выводится, тест есть и он проходит

2017-04-27 07:08 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +      redirect_to @question
Исправил, но все равно не понятно почему при редиректе выводились ошибки валидации

2017-04-27 07:09 UTC, Osshrp commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to have_content "Body can't be blank"
Да, проходил.
Исправил на рендер

2017-04-27 07:20 UTC, Osshrp commented on spec/acceptance/delete_spec.rb
> +  scenario 'Author tries to delete his question' do
Сделал

2017-04-27 07:40 UTC, Osshrp commented on spec/acceptance/view_question_spec.rb
> +    expect(page).to have_content 'AnswerText'
Сделано

2017-04-27 07:44 UTC, Osshrp commented on spec/controllers/answers_controller_spec.rb
>            .to change(Answer, :count).by(1)
сделано

2017-04-27 08:08 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def show
А зачем нам вид отдельного ответа? Почему не сдлеать удаление ответа сразу со страницы вопроса?

2017-04-27 08:08 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question
Ну потому что ты их сохраняешь в flash, то не верно. Ведь в этом случае не сохраняется то, что ввел пользователь, т.е. форма очищается, что неудобно.

2017-04-27 08:13 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +  def show
Ок, сейчас удалю

2017-04-27 08:23 UTC, vkurennov requested changes

2017-04-27 08:23 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      flash[:alert] = @answer.errors.full_messages
Вот это будет лишним, выводить ошибки нужно уже в виде, возле формы создания ответа

2017-04-27 08:23 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, only: [:create]
А почему только на create? Для destroy тоже нужен, например. Да и вообще, для всех экшенов

2017-04-27 08:23 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user && current_user.author_of?(@answer)
Если поставить фильтр authenticate_user на этот экшн (а его надо поставить), то проверка на current_user уже не нужна будет.

2017-04-27 08:23 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user && current_user.author_of?(@question)
Здесь не нужна проверка на `current_user`, потому что управление сюда не перейдет, если юзер не залогинен (у тебя же стоит фильтр)

2017-04-27 08:23 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user && current_user.author_of?(@question)
Тут тоже на current_user проверка не нужна

2017-04-27 08:23 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    flash.now[:alert] = @question.errors.full_messages
Не нужно выводить ошибки через флеш. Выводи их в форме

2017-04-27 08:23 UTC, vkurennov commented on app/views/questions/show.html.slim
> +        li.list-group-item = link_to answer.body, answer_path(answer)
Рекомендую сразу переделать этот вид так, чтобы здесь выводился ответ и все необходимые ссылки (например, на удаление). Это нам пригодится в следующих уроках, да так и удобнее (посмотри на оригинальный StackOverflow)

2017-04-27 08:23 UTC, vkurennov commented on spec/acceptance/view_question_spec.rb
> +    expect(page).to have_content question.answers.first.body
Вообще, лучше создать список из штук 5-ти ответов и проверить здесь их циклом

2017-04-27 08:23 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>        it 'saves new answer in database' do
Вот этот тест теперь лишний, хватит 2-х следующих

2017-04-27 08:23 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>        it 'saves new question in database' do
Опят же этот тетст лишний, т.к. в следующем проверяется то же самое, только еще и со связью

2017-04-27 08:23 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      @user.questions.create(attributes_for(:question, user: @user))
Надо буквально воспринять совет @iBublik, т.е. всю строку заменить:

`let!(:user_question) { create :question, user: @user }`

2017-04-27 08:23 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      @user.questions.create(attributes_for(:question, user: @user))
См. замечания для ответов

2017-04-27 08:23 UTC, vkurennov commented on spec/models/user_spec.rb
> +    expect(user_with_questions.author_of?(user_with_questions.questions.first)).to eq true
В rspec для методов-предикатов (на знак вопроса заканчиваются) есть особый синтаксис, можно писать так:

`expect(user_with_questions).to be_author_of(user_with_questions.questions.first)`

Т.е. метод переносим после `to`, добавляем `be_` и убираем знак вопроса

2017-04-27 08:28 UTC, webmstk commented on app/controllers/answers_controller.rb
> +      redirect_to @answer, notice: 'Your answer was successfully created'
после создания ответа мы должны увидеть его на странице вопроса :)

2017-04-27 08:37 UTC, Osshrp commented on spec/controllers/questions_controller_spec.rb
> +      @user.questions.create(attributes_for(:question, user: @user))
А-а-а, понял )

2017-04-27 08:51 UTC, webmstk commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, only: [:create]
удаление - тоже операция, которая требует аутентификации

2017-04-27 08:53 UTC, webmstk commented on app/controllers/answers_controller.rb
> +    if current_user && current_user.author_of?(@answer)
и здесь тогда не надо будет проверять  current_user (если поставишь `authenticate_user!` в `before_action`)

2017-04-27 08:55 UTC, webmstk commented on app/views/answers/show.html.slim
> +- if current_user && current_user.author_of?(@answer)
кстати, в руби 2.3.0 появился оператор безопасной навигации, можешь пользоваться, если синтаксис не коробит ))
```
if current_user&.author_of?(@answer)
```

2017-04-27 11:05 UTC, Osshrp commented on spec/controllers/questions_controller_spec.rb
> +      @user.questions.create(attributes_for(:question, user: @user))
Седлал

2017-04-27 11:06 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +  def show
Сделал

2017-04-27 11:12 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, only: [:create]
Исправил

2017-04-27 11:15 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +      flash[:alert] = @answer.errors.full_messages
Вот тут не понял.
Я во флеш пишу как раз для того чтобы ошибки выводились в виде возле формы создания

2017-04-27 11:15 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +    if current_user && current_user.author_of?(@answer)
Сделал

2017-04-27 11:16 UTC, Osshrp commented on app/controllers/questions_controller.rb
> +    if current_user && current_user.author_of?(@question)
Исправил

2017-04-27 11:17 UTC, Osshrp commented on app/controllers/questions_controller.rb
> +    if current_user && current_user.author_of?(@question)
Исправил

2017-04-27 11:22 UTC, Osshrp commented on app/views/questions/show.html.slim
> +        li.list-group-item = link_to answer.body, answer_path(answer)
Сделал ссылку на удаление

2017-04-27 11:23 UTC, webmstk commented on app/controllers/answers_controller.rb
> +      flash[:alert] = @answer.errors.full_messages
Обычно во флеше пишут уведомления о произошедших действиях (что-то успешно или не успешно создано, отказано в доступе, что-то было удалено).

А вывод ошибок делают во вьюхе. Во-первых, флеш может быть далеко от формы. Во-вторых, ошибок может быть много, и блок с флешем растянется (что не всегда приемлемо). В-третьих, когда захочется красиво оформить ошибки со стилями и html-тегами, оформлять всё это в контроллере не комильфо. Показывать ошибки заполнения формы - ответственность вьюхи.

2017-04-27 11:25 UTC, Osshrp commented on spec/acceptance/view_question_spec.rb
> +    expect(page).to have_content question.answers.first.body
сделал

2017-04-27 11:27 UTC, Osshrp commented on spec/controllers/answers_controller_spec.rb
>        it 'saves new answer in database' do
Убрал

2017-04-27 11:28 UTC, Osshrp commented on spec/controllers/questions_controller_spec.rb
>        it 'saves new question in database' do
Убрал

2017-04-27 11:30 UTC, Osshrp commented on spec/controllers/questions_controller_spec.rb
> +      @user.questions.create(attributes_for(:question, user: @user))
Исправил

2017-04-27 11:35 UTC, Osshrp commented on spec/models/user_spec.rb
> +    expect(user_with_questions.author_of?(user_with_questions.questions.first)).to eq true
Исправил, спасибо

2017-04-27 11:36 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +      redirect_to @answer, notice: 'Your answer was successfully created'
Исправлено

2017-04-27 11:36 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, only: [:create]
Исправлено

2017-04-27 11:36 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +    if current_user && current_user.author_of?(@answer)
Исправлено

2017-04-27 11:36 UTC, Osshrp commented on app/views/answers/show.html.slim
> +- if current_user && current_user.author_of?(@answer)
Ок

2017-04-27 11:39 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +      flash[:alert] = @answer.errors.full_messages
Так а как их показывать то?..
Ладно, пойду искать в документации

2017-04-27 11:43 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +      flash[:alert] = @answer.errors.full_messages
Что то типа`
`- if model.errors
  = model.errors.full_messages`

2017-04-27 11:44 UTC, webmstk commented on app/controllers/answers_controller.rb
> +      flash[:alert] = @answer.errors.full_messages
Не очень понятно, что именно не понятно :) Спрашиваешь у объекта, есть ли в нём ошибки. Если ошибки есть, выводишь сообщения циклом.

2017-04-27 12:15 UTC, Osshrp commented on app/controllers/answers_controller.rb
> +      flash[:alert] = @answer.errors.full_messages
Исправил

2017-04-27 12:16 UTC, Osshrp commented on app/controllers/questions_controller.rb
> +    flash.now[:alert] = @question.errors.full_messages
Исправлено

2017-04-27 15:38 UTC, webmstk commented on spec/acceptance/create_answer_spec.rb
> +    click_on 'Create answer'
Имеет смысл не показывать незалогиненному пользователю поле для ответа. Он напишет два метра текста, нажмёт создать ответ и ... всё :)

2017-04-27 15:57 UTC, webmstk commented on spec/models/user_spec.rb
> +  end
Обычно юнит тесты оборачивают в `describe` с названием тестируемого метода, чтобы было понятно, к чему относятся тесты
```
describe '#author_of' do
  # тесты метода объекта
end

describe '.notify_all' do
  # тесты метода класса
end
```

2017-04-27 16:11 UTC, Osshrp commented on spec/acceptance/create_answer_spec.rb
> +    click_on 'Create answer'
Сделал

2017-04-27 16:17 UTC, Osshrp commented on spec/models/user_spec.rb
> +  end
Сделал

2017-04-27 18:29 UTC, vkurennov approved these changes

2017-04-27 18:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> +      - if answer.invalid?
А зачем тут-то выводить ошибки? Выводи их в форме создания нового ответа

2017-04-28 10:29 UTC, merged