answers ajax
Osshrp/qna pull request #4
Opened 2017-04-28 13:00 UTC by Osshrp

2017-04-28 13:49 UTC, vkurennov requested changes

2017-04-28 13:49 UTC, vkurennov commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render "questions/answers" %>');
В задани же сказано: не рендерить весь список повторно, а добавлять только созданный ответ

2017-04-28 15:50 UTC, Osshrp commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render "questions/answers" %>');
Да, причем жирными буквами.
Прошу прощения.
Исправил

2017-04-28 17:10 UTC, vkurennov requested changes

2017-04-28 17:10 UTC, vkurennov commented on app/views/answers/create.js.erb
> +$('.answer').html('<%= j render "questions/answer", answer: @answer %>');
1. Так ты заменишь весь список ответов одним только что созданным.
2. Вспоминай тему про анонимные паршалы.

2017-04-28 17:17 UTC, Osshrp commented on app/views/answers/create.js.erb
> +$('.answer').html('<%= j render "questions/answer", answer: @answer %>');
Нет, это не так
класс answer присвоен диву, который расположен после списка вопросов.
Неудачное название класса, надо было назвать .last-answer
PS Я же проверил, работает как надо
всегда проверяю

2017-04-28 19:45 UTC, vkurennov commented on app/views/answers/create.js.erb
> +$('.answer').html('<%= j render "questions/answer", answer: @answer %>');
Сорри, не заметил, прочитал как answers. Но это тоже не лучший вариант. Ведь гораздо лучше не создавать див для нового ответа, а использовать функцию, добавляющую элемент к списку.
Ну и замечание про анонимные паршалы остается в силе.

2017-04-28 19:47 UTC, Osshrp commented on app/views/answers/create.js.erb
> +$('.answer').html('<%= j render "questions/answer", answer: @answer %>');
Ок, завтра сделаю

2017-04-29 18:21 UTC, vkurennov approved these changes

2017-04-29 18:21 UTC, vkurennov commented on app/views/answers/create.js.erb
> +$('.answers').append('<%= j render "answers/answer", answer: @question.answers.last %>');
Почему last-то? Добавлять надо созданный ответ (@answer), а он не обязательно последний (ведь кто-то еще мог создать овтет почти одновременно, но в базе он будет последний).
И вспомни, наконец, про анонимные паршалы. У тебя уже все есть, только ты их не используешь, можно записать так: `render @answer`

2017-04-30 04:44 UTC, Osshrp commented on app/views/answers/create.js.erb
> +$('.answers').append('<%= j render "answers/answer", answer: @question.answers.last %>');
Ссори не понял сначала, я думал, что ты говоришь про анонимный паршал в `questions/show`, я его там и применил для коллекции `@quesiton.answers`. Не знал, что анонимные паршалы можно применять не только для коллекций

2017-04-30 05:23 UTC, merged