L30
Osshrp/qna pull request #7
Opened 2017-05-20 10:18 UTC by Osshrp

2017-05-20 15:01 UTC, vkurennov requested changes

2017-05-20 15:01 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +        @votable.send("#{params[:vote]}_by", current_user)
Опасно вызывать методы из параметра. Это потенциальная дыра в безопасности. Лучше на основе параметра в явном виде вызывать нужный метод

2017-05-20 15:01 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  before_action :set_question, only: [:show, :update, :destroy, :set_like]
Что за set_like?

2017-05-20 15:01 UTC, vkurennov commented on app/models/concerns/attachable.rb
> +    belongs_to :user
Это не относится к аттачментам. Модель может иметь связь с юзером, но быть без аттачмента

2017-05-20 15:01 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    accepts_nested_attributes_for :votes
Это зачем? Нестед используется, когда родительский и дочерний объекты создаются одновременно.  А голос явно создаётся после

2017-05-20 15:01 UTC, vkurennov commented on app/models/concerns/votable.rb
> +      votes.create(value: "like", user: user)
Храни числовые значения рейтинга, тогда легко считать сумму

2017-05-20 15:01 UTC, vkurennov commented on app/models/concerns/votable.rb
> +
Это все должно быть в транзакции, иначе может быть так, что голос создан, а рейтинг не обновлён

2017-05-20 15:01 UTC, vkurennov commented on app/models/concerns/votable.rb
> +      vote.value == "like" ? self.rating -= 1 : self.rating += 1
Вообще, лучше пересчитывать рейтинг, считая общую сумму всех голосов, это надёжнее

2017-05-20 15:01 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +    <div id = "rate-answer-#{answer.id}">
это же слип, откуда тут угловые скобки?

2017-05-21 06:51 UTC, Osshrp commented on app/views/answers/_answer.html.slim
> +    <div id = "rate-answer-#{answer.id}">
Исправил

2017-05-21 06:51 UTC, Osshrp commented on app/models/concerns/votable.rb
> +
Сделал

2017-05-21 09:31 UTC, Osshrp commented on app/models/concerns/votable.rb
> +    accepts_nested_attributes_for :votes
Убрал

2017-05-21 09:32 UTC, Osshrp commented on app/controllers/questions_controller.rb
> +  before_action :set_question, only: [:show, :update, :destroy, :set_like]
Это мусор остался от предыдущей реализации.
Убрал

2017-05-21 09:33 UTC, Osshrp commented on app/controllers/concerns/voted.rb
> +        @votable.send("#{params[:vote]}_by", current_user)
Переделал

2017-05-21 10:10 UTC, Osshrp commented on app/models/concerns/attachable.rb
> +    belongs_to :user
Ну я таким образом хотел задраить код, пользуясь случаем туда еще и belongs_to user всунуть:)

2017-05-21 10:35 UTC, Osshrp commented on app/controllers/concerns/voted.rb
> +        @votable.send("#{params[:vote]}_by", current_user)
Еще раз переделал. Не нравятся мне многоэтажные if

2017-05-21 18:36 UTC, iBublik requested changes

2017-05-21 18:36 UTC, iBublik commented on app/assets/javascripts/votes.coffee
> +  if vote == null
В js null является логически эквивалентным false, так что можно было поменять ветки местами и убрать это странное сравнение.
А еще можно отрефакторить и сократить ветвление/дублирование. Вычисление селектора (`type` + `votable.id`) вынести в переменную. Установка `votable.rating` повторяется в обеих ветках. Какой текст писать в `#vote` можно определить по значению `vote` (если null - пустая строка, иначе нужный текст). Скрытие/закрытие формы голосавания и отмены голоса можно сделать с помощью `toggle`

2017-05-21 18:36 UTC, iBublik commented on app/controllers/concerns/voted.rb
> +      unless current_user.author_of?(@votable)
`unless` + `else` - зло. Поменяй местами и будет лучше восприниматься

2017-05-21 18:36 UTC, iBublik commented on app/controllers/concerns/voted.rb
> +        format.html { redirect_to questions_path,
Как-то странно - если голосует автор ресурса, то он это делает с html-форматом, а если не автор - то с json форматом?

2017-05-21 18:36 UTC, iBublik commented on app/controllers/concerns/voted.rb
> +  def set_like
Название метода не очень удачное - тут мы можем проголосовать и за, и против, и отменить голос.

2017-05-21 18:36 UTC, iBublik commented on app/models/concerns/votable.rb
> +    unless voted_by?(user)
Сделай `return if voted_by?(user)`, чтоб сразу выйти из метода и избавиться от лишней вложенности

2017-05-21 18:36 UTC, iBublik commented on app/models/concerns/votable.rb
> +      transaction do
В этой транзакции нет смысла - она никогда не откатится. Откат транзакции происходит только если блок бросил исключение, поэтому надо использовать бэнг-методы

2017-05-21 18:36 UTC, iBublik commented on app/models/vote.rb
> +  def self.show(value)
Почему это метод класса, а не инстанса?

2017-05-21 18:36 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +        - if answer.votes.first
А что, первый голос - это всегда голос текущего юзера?

2017-05-21 18:36 UTC, iBublik commented on db/migrate/20170519071413_change_is_likedto_value_in_votes.rb
> +    rename_column :votes, :is_liked, :value
Не нужно плодить миграции с переименованием полей, созданных в рамках этой фичи. Пока фича не слита в стабильную ветку, можно менять миграции. Иначе папка миграций распухнет от ненужной информации

2017-05-22 05:24 UTC, Osshrp commented on app/assets/javascripts/votes.coffee
> +  if vote == null
> Установка votable.rating повторяется в обеих ветках. Какой текст писать в #vote можно определить по значению vote (если null - пустая строка, иначе нужный текст)

Если пользователь отказался от голоса, то vote будет  null и надо рейтинг пересчитывать

2017-05-22 05:59 UTC, Osshrp commented on app/models/concerns/votable.rb
> +      transaction do
> Это все должно быть в транзакции, иначе может быть так, что голос создан, а рейтинг не обновлён

Сенсей сказал обернуть в транзакцию. И, да, разве транзакция используется только для того, чтобы все откатить назад? Я думал, что еще одна причина - это выполнить несколько команд в атомарном состоянии.

2017-05-22 06:03 UTC, iBublik commented on app/models/concerns/votable.rb
> +      transaction do
Транзакция нужна, просто ее надо правильно готовить :)
> Откат транзакции происходит только если блок бросил исключение, поэтому надо использовать бэнг-методы

2017-05-22 06:15 UTC, Osshrp commented on app/models/concerns/votable.rb
> +      transaction do
Пошел читать про бэнг-методы :)

2017-05-22 07:32 UTC, Osshrp commented on app/models/vote.rb
> +  def self.show(value)
Внятно ответить не могу :) Мне так показалось, что ему в инстансе не место

2017-05-22 09:39 UTC, iBublik commented on app/models/vote.rb
> +  def self.show(value)
Посмотри как ты вызываешь этот метод - `Vote.show(@vote.value) if @vote`. Хотя можно было бы сделать метод инстанса и писать `@vote&.display_value`

2017-05-22 11:18 UTC, Osshrp commented on app/assets/javascripts/votes.coffee
> +  if vote == null
После рефакторинга все сломалось...
Уже несколько часов убил, ничего понять не могу.
Если попытаться отменить голос для вопроса, то не появляется форма голосования.
При этом я в инспекторе вижу как у формы меняется стиль с display: none на dispay: block
Но форма все равно не показывается :(
Даже, если в консоли вызывать `$('form#vote-answer-41').toggle()`,
то все равно не работает.
Если страницу перезагрузить и вызывать из консоли, то все нормально...
git-ом откатил изменения - не помогло

2017-05-22 14:57 UTC, Osshrp commented on app/assets/javascripts/votes.coffee
> +  if vote == null
Починил :)

2017-05-22 16:33 UTC, Osshrp commented on app/models/vote.rb
> +  def self.show(value)
Все таки метод класса лучше.
Если для question @vote можно в #show загрузить, то для answer, так как он рендерится из вьюхи question show адский адище получается:
vote - это хелпер(принимает инстанс и возвращает vote для current_user), без него полный армагедон
`vote(answer)&.show(vote(answer).value`

2017-05-22 16:51 UTC, Osshrp commented on app/views/answers/_answer.html.slim
> +        - if answer.votes.first
Ага, исправил

2017-05-22 16:51 UTC, Osshrp commented on db/migrate/20170519071413_change_is_likedto_value_in_votes.rb
> +    rename_column :votes, :is_liked, :value
Понял

2017-05-23 05:18 UTC, iBublik commented on app/controllers/concerns/voted.rb
> +        format.json { render json: { resource: controller_name.singularize ,
По-прежнему не понимаю почему в одном случае `format.html`, а в другом - `format.json`

2017-05-23 05:18 UTC, iBublik commented on app/models/concerns/votable.rb
> +    scope :test, ->(user, votable) { joins(:votes).where(user: user, votable_id: votable) }
Что за `test`? :)

2017-05-23 05:18 UTC, iBublik commented on app/models/concerns/votable.rb
> +      self.rating += 1
На будущее - лучше используй [increment_counter](http://api.rubyonrails.org/classes/ActiveRecord/CounterCache/ClassMethods.html#method-i-increment_counter). Иначе возможный race condition'ы (два пользователя нажали лайк примерно одновременно, а рейтинг обновился только на 1)

2017-05-23 05:18 UTC, iBublik commented on app/models/concerns/votable.rb
> +        vote = votes.where(user: user).first
Ниже есть метод `vote`, который делает то же самое

2017-05-23 05:18 UTC, iBublik commented on app/models/vote.rb
> +  def show(value)
А зачем значение-то передавать? Объект ведь в себе это значение содержит. Просто
```ruby
def show
  # self не нужен, просто заостряю внимание, что это атрибут модели
  { 1 => :like, -1 => :dislike }[self.value]
end
```

2017-05-23 05:18 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +        | You've #{vote(answer)&.show(vote(answer).value)}d it
Зачем safe navigation, если выше была проверка на наличие голоса за ответ?

2017-05-23 05:18 UTC, iBublik commented on app/views/questions/_question.html.slim
> +    | You've #{vote&.show(vote.value)}d it
Опять же, зачем тут safe navigation?

2017-05-23 05:18 UTC, iBublik commented on db/migrate/20170519071413_change_is_likedto_value_in_votes.rb
> +    rename_column :votes, :is_liked, :value
Почисти все же миграции, слишком много исправлений нового функционала

2017-05-23 07:27 UTC, vkurennov requested changes

2017-05-23 07:27 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +        format.json { render json: { resource: controller_name.singularize ,
Да, почему в одном случае ты отдаешь html, а в другом json, если у тебя запрос в json приходит? Нужно, если это автор отдать статуст 403 (forbidden) и на клиенте его обработать, например, вывести сообщение.

2017-05-23 07:27 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    vote = { "like" => :like_by, "dislike" => :dislike_by, "clear_vote" => :clear_vote_by }
Может, стоило и методы назвать like, dislike, clear_vote? Тогда бы достаточно массива было бы

2017-05-23 07:27 UTC, vkurennov commented on config/routes.rb
> +      patch :vote, on: :member
Используй консерны в роутах

2017-05-23 17:25 UTC, vkurennov approved these changes

2017-05-24 05:29 UTC, merged